pipeline:
  test:
    image: maven:3-jdk-8
    environment:
      MAVEN_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -DdependencyLocationsEnabled=false -Djava.net.preferIPv4Stack=true
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -T 2C
      - mvn test -B
    when:
      branch: master
      event: pull_request

  publish-staging:
    image: plugins/docker
    repo: devheavenci/project-management-service
    tags: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  publish-production:
    image: plugins/docker
    repo: devheavenci/project-management-service
    tags: "${DRONE_TAG##v}"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  deploy-staging:
    image: quay.io/honestbee/drone-kubernetes
    namespace: staging
    deployment: project-management-deployment
    repo: devheavenci/project-management-service
    container: project-management
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      branch: master
      event: push

  deploy-production:
    image: quay.io/honestbee/drone-kubernetes
    namespace: production
    deployment: project-management-deployment
    repo: devheavenci/project-management-service
    container: project-management
    tag: "${DRONE_TAG##v}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      event: tag

branches: master
