pipeline:
  test:
    image: openjdk:8-jdk
    commands:
      - ./gradlew compileJava
      - ./gradlew build --quiet --stacktrace
      - ./gradlew test --tests 'nl.devheaven.service*' --quiet
    when:
      branch: master
      event: pull_request

  code-analysis:
    image: ypcloud/sonar-runner
    host: "https://sonar.devheaven.nl"
    sources: "./src/main/java"
    profile: "Sonar way"
    language: "java"
    secrets: [ sonar_login, sonar_password ]
    when:
      branch: master
      event: pull_request

  publish-staging:
    image: plugins/docker
    repo: devheavenci/project-management-service
    tags: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push

  publish-production:
    image: plugins/docker
    repo: devheavenci/project-management-service
    tags: "${DRONE_TAG##v}"
    secrets: [ docker_username, docker_password ]
    when:
      event: tag

  deploy-staging:
    image: quay.io/honestbee/drone-kubernetes
    namespace: staging
    deployment: project-management-deployment
    repo: devheavenci/project-management-service
    container: project-management
    tag: "${DRONE_COMMIT_SHA:0:8}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      branch: master
      event: push

  deploy-production:
    image: quay.io/honestbee/drone-kubernetes
    namespace: production
    deployment: project-management-deployment
    repo: devheavenci/project-management-service
    container: project-management
    tag: "${DRONE_TAG##v}"
    secrets: [ kubernetes_server, kubernetes_token, kubernetes_cert ]
    when:
      event: tag

branches: master
