spring:
  datasource:
    url: jdbc:h2:mem:devheaven-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: null
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  kafka:
    enabled: false
    bootstrap-servers: localhost:9092
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: project-management-service
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

security:
  jwt:
    header: Authorization
    prefix: Bearer
    secret: x4LLr8wgB5TvfALpcncfrxDwz2BQYhMC

springfox:
  documentation:
    swagger:
      v2:
        path: '/docs/'
